### PR TITLE
docs: fix typo in command

### PR DESCRIPTION
**Pull request by ArjixWasTaken**

### CODE REVIEW

**Review by aklinker1 — APPROVED** [review]

**Comment by aklinker1** [comment]
Whelp, weird that checks are failing like this. Time to do some maintainence on this repo...

**Comment by ArjixWasTaken** [comment]
Since it fails at installing pnpm, I suggest enabling nodejs' corepack

**Comment by aklinker1** [comment]
Oh woops, I actually updated this section in #66... I migrated to a Nuxt app for docs and reviewed all the pages. I updated my suggestion from `vite-plugin-web-extension` to WXT: https://webext-core.aklinker1.io/get-started/introduction#bundler-setup

**Comment by ArjixWasTaken** [comment]
it's ok

**Pull request closed without merging**
