### PR TITLE
chore(messaging): Share messaging logic and types for more implementations

### LINKED ISSUE #27: Feature request: Add the ability to talk with window / injected script
Please add the ability to talk with window / injected script, perhaps as another package that extend `messaging` package? 
such as `webext-core/window-messaging`

then we can call background script even in window context or sending data to window.

### PR DESCRIPTION
**Pull request by aklinker1**
### Overview

Refactor to make #27 easier to implement. I'm now shared all the `defineMessenger` logic and types.

### CODE REVIEW

**Comment by devnomic** [comment]
I think maybe it's better to add namespace option in `defineWindowMessaging` to prevent collision with other ext.

**Comment by aklinker1** [comment]
I can add that.

**Comment by aklinker1** [comment]
> I think maybe it's better to add namespace option in `defineWindowMessaging` to prevent collision with other ext.

I'm just going to use `browser.runtime.id` for this. That should be unique across extensions on all browsers. @devnomic with that, do you still think a namespace option for `defineWindowMessenger` is required?

**Comment by devnomic** [comment]
> > I think maybe it's better to add namespace option in `defineWindowMessaging` to prevent collision with other ext.
> 
> I'm just going to use `browser.runtime.id` internally for this. It should be unique across extensions on all browsers, preventing accidental communication. @devnomic with that, do you still think a namespace option for `defineWindowMessenger` is required?
> 
> _Edit: Unless you want to communicate with other extensions, that would disallow that. I think I'll add an optional `namespace` option that defaults to `browser.runtime.id`, but it can be overrided to something else if needed. That should cover all cases._

Yeah that would be the best.

**Comment by aklinker1** [comment]
Pulled the new messengers features out into #33

**Pull request merged**
